services:
  watcharr:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: watcharr
    ports:
      - 3080:3080
    volumes:
      - watcharr_data:/data
    restart: unless-stopped

volumes:
  watcharr_data:
