services:
  watcharr2:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: watcharr2
    ports:
      - 3080:3080
    volumes:
      - watcharr_data1:/data
    restart: unless-stopped

volumes:
  watcharr_data1:
