services:
  watcharr:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: watcharr
    ports:
      - 3081:3080
    volumes:
      - watcharr_data1:/data
    restart: unless-stopped

volumes:
  watcharr_data1:
